superbuild_add_project(assimp
  LICENSE_FILES
    LICENSE
  CMAKE_ARGS
    -DASSIMP_NO_EXPORT=ON
    -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=OFF
    -DASSIMP_BUILD_FBX_IMPORTER=ON
    -DASSIMP_BUILD_OFF_IMPORTER=ON
    -DASSIMP_BUILD_COLLADA_IMPORTER=ON
    -DASSIMP_BUILD_DXF_IMPORTER=ON
    -DASSIMP_BUILD_TESTS=OFF
    -DASSIMP_BUILD_ASSIMP_TOOLS=OFF
    -DASSIMP_BUILD_SAMPLES=OFF
    -DASSIMP_WARNINGS_AS_ERRORS=OFF
    -DBUILD_SHARED_LIBS=OFF
    -DCMAKE_MACOSX_RPATH=OFF
    -DCMAKE_BUILD_TYPE=Release
)

superbuild_apply_patch(assimp remove-debug-flags-windows
  "Remove Windows debug flags")
