superbuild_add_project(assimp
  BUILD_SHARED_LIBS_INDEPENDENT
  LICENSE_FILES
    LICENSE
  DEPENDS zlib
  CMAKE_ARGS
    -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT:BOOL=OFF
    -DASSIMP_BUILD_ASSIMP_TOOLS:BOOL=OFF
    -DASSIMP_BUILD_COLLADA_IMPORTER:BOOL=ON
    -DASSIMP_BUILD_DXF_IMPORTER:BOOL=ON
    -DASSIMP_BUILD_FBX_IMPORTER:BOOL=ON
    -DASSIMP_BUILD_OFF_IMPORTER:BOOL=ON
    -DASSIMP_BUILD_SAMPLES:BOOL=OFF
    -DASSIMP_BUILD_TESTS:BOOL=OFF
    -DASSIMP_BUILD_ZLIB:BOOL=OFF
    -DASSIMP_NO_EXPORT:BOOL=ON
    -DASSIMP_WARNINGS_AS_ERRORS:BOOL=OFF
)
