superbuild_add_project(openexr
  BUILD_SHARED_LIBS_INDEPENDENT
  LICENSE_FILES
    LICENSE.md
  DEPENDS imath zlib
  CMAKE_ARGS
    -DOPENEXR_INSTALL_TOOLS=OFF
    -DOPENEXR_INSTALL_EXAMPLES=OFF
    -DCMAKE_BUILD_TYPE=Release
    -DCMAKE_MACOSX_RPATH=OFF
)
