version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directories:
      - "/.github/actions/*/"
    labels:
      - "source:CI"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "actions/*"
